name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create deployment ZIP
        run: |
          zip -r deployment_package.zip .
        working-directory: ${{ github.workspace }}

      - name: Upload deployment artifact
        uses: actions/upload-artifact@v2
        with:
          name: lambda-deployment
          path: deployment_package.zip

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code --function-name HelloLambda \
            --zip-file fileb://$GITHUB_WORKSPACE/deployment_package.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
